### Registration new user
POST http://localhost:5000/api/auth/registration HTTP/1.1
Content-Type: application/json

{
  "fullName": "Will Smith",
  "email": "Will.Smith@Gmail.com",
  "password": "Qwerty12"
}

### Login user
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  # "email": "WILL.smith@GMAIL.com",
  # "password": "Qwerty12",
  "email": "Upd.User222@Gmail.com",
  "password": "Qwerty1234567"
}

### Logout user
GET http://localhost:5000/api/auth/logout HTTP/1.1
Content-Type: application/json

### Get new Access token by Refresh token
GET http://localhost:5000/api/auth/refresh HTTP/1.1
Content-Type: application/json

### Get list all users
GET http://localhost:5000/api/auth/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlVwZC5Vc2VyQEdtYWlsLmNvbSIsImlhdCI6MTcyODc4MzI4NSwiZXhwIjoxNzI4Nzg0NDg1fQ.GCOkMcGFKCPZEKM7zIEmLUQwb5RAE142PUVSqd2kt_c

### Get user by id
GET http://localhost:5000/api/auth/users/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbGwuc21pdGhAZ21haWwuY29tIiwiaWF0IjoxNzI4NzgxNDg0LCJleHAiOjE3Mjg3ODI2ODR9.ynmxce4-yB7qXSnKpjHo-CidzfYzzWp15O5b3ltzPxQ

### Update user data
PUT http://localhost:5000/api/auth/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlVwZC5Vc2VyMUBHbWFpbC5jb20iLCJpYXQiOjE3Mjg3ODQ1MTIsImV4cCI6MTcyODc4NTcxMn0.CIU11w7Js59JVduJ8XAMLrY8dGJaYv7N88M1XgQwifw

{
  "id": 2,
  "fullName": "Updated User",
  "email": "Upd.User@Gmail.com",
  "password": "Qwerty1234567"
}

### Delete current logged user
DELETE http://localhost:5000/api/auth/delete/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldJTEwuc21pdGhAR01BSUwuY29tIiwiaWF0IjoxNzI4NzgyMDQ0LCJleHAiOjE3Mjg3ODMyNDR9.6Q0AyDn2DqvY-5uEPz8UOirYdyXy8tmmLWicq2UJkkU