### Registration new user
POST http://localhost:5000/api/auth/registration HTTP/1.1
Content-Type: application/json

{
  "fullName": "Will Smith",
  "email": "Will.Smith@Gmail.com",
  "password": "Qwerty12"
}

### Login user
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "WILL.smith@GMAIL.com",
  "password": "Qwerty12"
}

// ==============================================================

### Logout user
GET http://localhost:5000/api/auth/logout HTTP/1.1
Content-Type: application/json

### Regenerate Tokens
GET http://localhost:5000/api/auth/refresh HTTP/1.1
Content-Type: application/json

// ==============================================================

### Get list all users
GET http://localhost:5000/api/auth/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldJTEwuc21pdGhAR01BSUwuY29tIiwiaWF0IjoxNzMwMTk3MzI0LCJleHAiOjE3MzAxOTgyMjR9.gXRQ3Ajmb-DyWGkUo0ppyP2ZTEpha5obwHA9l1eJ3fM

### Get current user profile
GET http://localhost:5000/api/auth/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldJTEwuc21pdGhAR01BSUwuY29tIiwiaWF0IjoxNzMwMTk3MzI0LCJleHAiOjE3MzAxOTgyMjR9.gXRQ3Ajmb-DyWGkUo0ppyP2ZTEpha5obwHA9l1eJ3fM

### Get user by id
GET http://localhost:5000/api/auth/users/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldJTEwuc21pdGhAR01BSUwuY29tIiwiaWF0IjoxNzMwMTk3MzI0LCJleHAiOjE3MzAxOTgyMjR9.gXRQ3Ajmb-DyWGkUo0ppyP2ZTEpha5obwHA9l1eJ3fM

// ==============================================================

### Update user data
PUT http://localhost:5000/api/auth/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldJTEwuc21pdGhAR01BSUwuY29tIiwiaWF0IjoxNzMwMTk3MzI0LCJleHAiOjE3MzAxOTgyMjR9.gXRQ3Ajmb-DyWGkUo0ppyP2ZTEpha5obwHA9l1eJ3fM

{
  "id": 2,
  "fullName": "Updated User",
  "email": "Updated.User@GMAIL.com",
  "password": "Qwerty1234567"
}

### Delete user by id
DELETE http://localhost:5000/api/auth/delete/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldJTEwuc21pdGhAR01BSUwuY29tIiwiaWF0IjoxNzMwMTk3MzI0LCJleHAiOjE3MzAxOTgyMjR9.gXRQ3Ajmb-DyWGkUo0ppyP2ZTEpha5obwHA9l1eJ3fM