import { builtinModules } from 'module';

import js from '@eslint/js';
import importPlugin from 'eslint-plugin-import';
import jsxA11Y from 'eslint-plugin-jsx-a11y';
import regexopt from 'eslint-plugin-optimize-regex';
import prettier from 'eslint-plugin-prettier';
import promise from 'eslint-plugin-promise';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import reactPerf from 'eslint-plugin-react-perf';
import reactRefresh from 'eslint-plugin-react-refresh';
import simpleImportSort from 'eslint-plugin-simple-import-sort';
import sortkeys from 'eslint-plugin-sort-keys-fix';
import unicorn from 'eslint-plugin-unicorn';
import globals from 'globals';

export default [
  {
    files: ['**/*.{js,jsx}'],
    ignores: ['dist'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parserOptions: {
        ecmaFeatures: { jsx: true },
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
    },
    plugins: {
      import: importPlugin,
      'jsx-a11y': jsxA11Y,
      'optimize-regex': regexopt,
      prettier,
      promise,
      react,
      'react-hooks': reactHooks,
      'react-perf': reactPerf,
      'react-refresh': reactRefresh,
      'simple-import-sort': simpleImportSort,
      'sort-keys-fix': sortkeys,
      unicorn,
    },
    rules: {
      ...js.configs.recommended.rules,
      ...react.configs.recommended.rules,
      ...react.configs['jsx-runtime'].rules,
      ...reactHooks.configs.recommended.rules,
      'array-bracket-newline': ['warn', 'consistent'],
      'array-callback-return': 'error',
      'arrow-body-style': 'warn',
      'block-scoped-var': 'error',
      'block-spacing': ['warn', 'always'],
      camelcase: ['warn', { properties: 'always' }],
      'capitalized-comments': ['off', 'always'],
      'class-methods-use-this': 'error',
      'comma-dangle': ['off', 'always-multiline'],
      'comma-spacing': [
        'warn',
        {
          after: true,
          before: false,
        },
      ],
      'consistent-return': 'warn',
      curly: ['warn', 'all'],
      'default-case': 'error',
      'default-case-last': 'error',
      'default-param-last': 'warn',
      'dot-location': ['warn', 'property'],
      'eol-last': ['error', 'always'],
      eqeqeq: 'error',
      'for-direction': 'error',
      'func-call-spacing': 'error',
      'func-name-matching': 'warn',
      'func-names': ['warn', 'always'],
      'generator-star-spacing': 'error',
      'getter-return': 'error',
      'global-require': 'off',
      'guard-for-in': 'warn',
      'import/default': 'error',
      'import/exports-last': 'warn',
      'import/extensions': [
        'warn',
        'never',
        { css: 'always', json: 'always', scss: 'always' },
      ],
      'import/first': 'error',
      'import/named': 'error',
      'import/newline-after-import': ['warn', { count: 1 }],
      'import/no-absolute-path': 'error',
      'import/no-amd': 'error',
      'import/no-commonjs': 'error',
      'import/no-duplicates': 'error',
      'import/no-extraneous-dependencies': ['error', { devDependencies: true }],
      'import/no-mutable-exports': 'error',
      'import/no-named-as-default': 'warn',
      'import/no-named-as-default-member': 'warn',
      'import/no-self-import': 'error',
      'import/no-unresolved': 'error',
      'import/no-useless-path-segments': 'error',
      'import/unambiguous': 'error',
      'init-declarations': ['warn', 'always'],
      'jsx-a11y/alt-text': 'warn',
      'jsx-a11y/anchor-is-valid': 'warn',
      'jsx-a11y/no-noninteractive-element-to-interactive-role': 'error',
      'lines-between-class-members': [
        'error',
        'always',
        { exceptAfterSingleLine: true },
      ],
      'max-classes-per-file': ['error', 1],
      'max-nested-callbacks': ['error', 5],
      'new-cap': 'off',
      'new-parens': 'error',
      'no-alert': 'error',
      'no-array-constructor': 'warn',
      'no-await-in-loop': 'error',
      'no-bitwise': 'warn',
      'no-caller': 'error',
      'no-confusing-arrow': 'error',
      'no-console': 'off',
      'no-const-assign': 'error',
      'no-constructor-return': 'error',
      'no-continue': 'error',
      'no-control-regex': 'error',
      'no-div-regex': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-duplicate-imports': 'error',
      'no-else-return': ['error', { allowElseIf: false }],
      'no-empty-character-class': 'error',
      'no-empty-function': 'error',
      'no-empty-pattern': 'error',
      'no-eval': 'error',
      'no-ex-assign': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-extra-parens': ['error', 'functions'],
      'no-fallthrough': 'error',
      'no-floating-decimal': 'error',
      'no-func-assign': 'error',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-inline-comments': 'warn',
      'no-invalid-regexp': 'error',
      'no-invalid-this': 'error',
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'warn',
      'no-lonely-if': 'warn',
      'no-loop-func': 'error',
      'no-mixed-operators': [
        'error',
        {
          groups: [
            ['*', '/', '%', '**'],
            ['+', '-'],
            ['&', '|', '^', '~', '<<', '>>', '>>>'],
            ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
            ['&&', '||'],
            ['in', 'instanceof'],
          ],
        },
      ],
      'no-mixed-requires': 'error',
      'no-multi-assign': 'warn',
      'no-multi-spaces': 'warn',
      'no-multi-str': 'warn',
      'no-multiple-empty-lines': ['error', { max: 1 }],
      'no-native-reassign': 'error',
      'no-negated-condition': 'error',
      'no-negated-in-lhs': 'error',
      'no-nested-ternary': 'warn',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-object': 'warn',
      'no-new-symbol': 'error',
      'no-new-wrappers': 'error',
      'no-obj-calls': 'error',
      'no-octal': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': [
        'error',
        {
          ignorePropertyModificationsFor: ['state', 'acc', 'config'],
          props: true,
        },
      ],
      'no-path-concat': 'error',
      'no-promise-executor-return': 'error',
      'no-proto': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-restricted-globals': 'error',
      'no-restricted-properties': [
        'error',
        {
          message:
            'Please use import() instead. More info: https://facebook.github.io/create-react-app/docs/code-splitting',
          object: 'require',
          property: 'ensure',
        },
        {
          message:
            'Please use import() instead. More info: https://facebook.github.io/create-react-app/docs/code-splitting',
          object: 'System',
          property: 'import',
        },
      ],
      'no-restricted-syntax': [
        'error',
        'WithStatement',
        // {
        //   selector: "LogicalExpression[operator='||']",
        //   message:
        //     'Используйте ?? вместо || для проверки на null или undefined.',
        // },
      ],
      'no-return-assign': 'error',
      'no-return-await': 'error',
      'no-script-url': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'error',
      'no-this-before-super': 'error',
      'no-throw-literal': 'error',
      'no-trailing-spaces': 'warn',
      'no-undef': 'error',
      'no-undef-init': 'error',
      'no-undefined': 'warn',
      'no-underscore-dangle': [
        'error',
        {
          allow: ['_id', '_retry'],
        },
      ],
      'no-unmodified-loop-condition': 'error',
      'no-unneeded-ternary': 'error',
      'no-unreachable': 'error',
      'no-unreachable-loop': 'error',
      'no-unsafe-optional-chaining': [
        'warn',
        {
          disallowArithmeticOperators: true,
        },
      ],
      'no-unused-expressions': [
        'error',
        {
          allowShortCircuit: true,
          allowTernary: true,
        },
      ],
      'no-unused-labels': 'error',
      'no-unused-vars': 'warn',
      'no-use-before-define': ['error', { classes: true, functions: true }],
      'no-useless-backreference': 'error',
      'no-useless-call': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'error',
      'no-useless-constructor': 'error',
      'no-useless-escape': 'error',
      'no-useless-rename': [
        'error',
        {
          ignoreDestructuring: false,
          ignoreExport: false,
          ignoreImport: false,
        },
      ],
      'no-useless-return': 'error',
      'no-var': 'error',
      'no-void': 'error',
      'no-warning-comments': 'warn',
      'no-with': 'error',
      'object-curly-newline': ['warn', { consistent: true }],
      'object-curly-spacing': ['warn', 'always'],
      'object-shorthand': 'warn',
      'one-var': ['warn', 'never'],
      'one-var-declaration-per-line': ['error', 'always'],
      'operator-assignment': 'error',
      'optimize-regex/optimize-regex': 'warn',
      'prefer-arrow-callback': 'warn',
      'prefer-const': ['warn', { destructuring: 'all' }],
      'prefer-destructuring': [
        'warn',
        {
          AssignmentExpression: {
            array: false,
            object: false,
          },
          VariableDeclarator: {
            array: true,
            object: true,
          },
        },
      ],
      'prefer-object-spread': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': 'error',
      'prefer-spread': 'warn',
      'prefer-template': 'warn',
      'prettier/prettier': 'warn',
      'promise/always-return': 'warn',
      'promise/catch-or-return': 'warn',
      'promise/no-nesting': 'warn',
      'promise/no-return-wrap': 'warn',
      'promise/prefer-await-to-then': 'warn',
      'react-hooks/exhaustive-deps': 'warn',
      'react-hooks/rules-of-hooks': 'error',
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      'react/boolean-prop-naming': [
        'warn',
        { rule: '^(is|has|can)[A-Z]([A-Za-z0-9]?)+' },
      ],
      'react/destructuring-assignment': ['error', 'always'],
      'react/display-name': 'error',
      'react/function-component-definition': [
        'error',
        { namedComponents: 'function-declaration' },
      ],
      'react/jsx-filename-extension': [
        'warn',
        {
          extensions: ['.js', '.jsx'],
        },
      ],
      'react/jsx-fragments': ['error', 'syntax'],
      'react/jsx-key': 'error',
      'react/jsx-no-constructed-context-values': 'error',
      'react/jsx-no-duplicate-props': 'error',
      'react/jsx-no-target-blank': ['warn', { allowReferrer: false }],
      'react/jsx-no-undef': 'error',
      'react/jsx-no-useless-fragment': ['warn', { allowExpressions: true }],
      'react/jsx-pascal-case': 'error',
      'react/jsx-sort-props': [
        'warn',
        {
          callbacksLast: true,
          ignoreCase: true,
          reservedFirst: true,
          shorthandFirst: true,
        },
      ],
      'react/no-access-state-in-setstate': 'error',
      'react/no-children-prop': 'error',
      'react/no-danger': 'error',
      'react/no-direct-mutation-state': 'error',
      'react/no-multi-comp': ['error', { ignoreStateless: true }],
      'react/no-render-return-value': 'warn',
      'react/no-typos': 'error',
      'react/no-unescaped-entities': 'warn',
      'react/no-unstable-nested-components': ['error', { allowAsProps: true }],
      'react/no-unused-prop-types': 'warn',
      'react/no-unused-state': 'warn',
      'react/prefer-stateless-function': [
        'error',
        { ignorePureComponents: true },
      ],
      'react/prop-types': 'off',
      'react/require-default-props': 'warn',
      'react/require-render-return': 'warn',
      'react/self-closing-comp': 'warn',
      'react/sort-comp': [
        'error',
        {
          order: [
            'static-methods',
            'instance-variables',
            'lifecycle',
            'render',
            '/^handle.+$/',
            '/^on.+$/',
            'everything-else',
          ],
        },
      ],
      'react/void-dom-elements-no-children': 'error',
      'require-atomic-updates': 'error',
      'require-await': 'error',
      'require-yield': 'error',
      'simple-import-sort/exports': 'warn',
      'simple-import-sort/imports': [
        'warn',
        {
          groups: [
            [`^(${builtinModules.join('|')})(/|$)`],
            [
              '^react',
              '^react-dom',
              '^react-helmet-async',
              '^react-router-dom',
              '^react-redux',
              '^@reduxjs/toolkit',
              '^redux-logger',
              '^axios',
              '^chart.js',
              '^chartjs-plugin-datalabels',
              '^react-chartjs-2',
              '^date-fns',
              '^formik',
              '^yup',
              '^@?\\w',
            ],
            ['^@fortawesome'],
            ['^@mui/material'],
            ['^@mui/x-date-pickers'],
            [
              '^@mui/material/styles',
              '^@mui/material/useMediaQuery',
              '^@mui/material/locale',
            ],
            ['^@mui/icons-material'],
            [
              '^.*\\/constants($|\\/.*$)',
              '^.*\\/utils($|\\/.*$)',
              '^.*\\/api($|\\/.*$)',
              '^.*\\/hooks($|\\/.*$)',
            ],
            [
              '^.*\\/store($|\\/.*$)',
              '^.*\\/selectors($|\\/.*$)',
              '^.*\\/services($|\\/.*$)',
              '^.*\\/slices($|\\/.*$)',
              '^.*\\/thunks($|\\/.*$)',
            ],
            ['^.*\\/components($|\\/.*$)'],
            ['^.*\\/pages($|\\/.*$)'],
            ['^\\.\\.(?!/?$)', '^\\.\\./?$'],
            ['^\\./(?=.*/)(?!/?$)', '^\\.(?!/?$)', '^\\./?$'],
            ['^.*\\/App\\.jsx$'],
            ['^.*\\/assets($|\\/.*$)', '^.*\\/styles($|\\/.*$)', '^.*\\.css$'],
          ],
        },
      ],
      'sort-vars': ['warn', { ignoreCase: true }],
      'space-in-parens': ['error', 'never'],
      'spaced-comment': 'error',
      strict: ['error', 'never'],
      'symbol-description': 'error',
      'unicorn/no-array-for-each': 'warn',
      'unicorn/prefer-query-selector': 'warn',
      'valid-typeof': 'error',
      'vars-on-top': 'error',
      'wrap-regex': 'off',
      'yield-star-spacing': 'warn',
      yoda: 'error',
      // 'react/no-array-index-key': 'warn',
      // 'react/jsx-no-bind': ['warn', { allowArrowFunctions: false }],
      // 'sort-keys-fix/sort-keys-fix': 'warn',
      // 'react-perf/jsx-no-new-function-as-prop': 'warn',
      // 'react-perf/jsx-no-new-object-as-prop': 'warn',
      // 'react-perf/jsx-no-new-array-as-prop': 'warn',
    },
    settings: {
      'import/resolver': {
        node: {
          extensions: ['.js', '.jsx', '.json'],
        },
      },
      react: { version: '18' },
    },
  },
];
