module.exports = {
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_LIFETIME: process.env.ACCESS_TOKEN_LIFETIME,
  REFRESH_TOKEN_LIFETIME: process.env.REFRESH_TOKEN_LIFETIME,
  HASH_SALT_ROUNDS: parseInt(process.env.HASH_SALT_ROUNDS),
};
