### Get list of favorite cities
GET http://localhost:5000/api/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI3ODFmMGFkNC1jNjg3LTQ1Y2YtOTMzYS0xMzgzNmFiMWE3OWQiLCJpYXQiOjE3NDY1Njk4ODAsImV4cCI6MTc0NjU3MDc4MH0.3lcDm5Yzc0V0GdgCOtLdJbX2VttAnsfHUnpfWnH2DAQ

### Add city to favorites
POST http://localhost:5000/api/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI3ODFmMGFkNC1jNjg3LTQ1Y2YtOTMzYS0xMzgzNmFiMWE3OWQiLCJpYXQiOjE3NDY1Njk4ODAsImV4cCI6MTc0NjU3MDc4MH0.3lcDm5Yzc0V0GdgCOtLdJbX2VttAnsfHUnpfWnH2DAQ

{
  "city": "Zaporizhia",
  "countryCode": "UA",
  "latitude": 47.8167,
  "longitude": 35.1833
}

### Remove city from favorites
DELETE http://localhost:5000/api/favorites?latitude=47.8167&longitude=35.1833 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI3ODFmMGFkNC1jNjg3LTQ1Y2YtOTMzYS0xMzgzNmFiMWE3OWQiLCJpYXQiOjE3NDY1Njk4ODAsImV4cCI6MTc0NjU3MDc4MH0.3lcDm5Yzc0V0GdgCOtLdJbX2VttAnsfHUnpfWnH2DAQ
