### Get user profile
GET http://localhost:5000/api/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiJiYjM3M2IwNi1hZGQwLTRmYWUtYjJlYy1iODI3NWVjMTA3YjAiLCJpYXQiOjE3NDQ1NjE3MDcsImV4cCI6MTc0NDU2MjYwN30.Z9WATB-jVIrcETaIy5YndBCH99uwINoGKGnt32FdETg
