### Get list all users
GET http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiJmMGE4ZTUzYy03NmJhLTQ0Y2YtOWRiMC03MDVjMGU0ZWE3MzEiLCJpYXQiOjE3NDQ1NTM2NjksImV4cCI6MTc0NDU1NDU2OX0.CANOGmKo3U3smnVoxiIlDtta5YfeoJEdai5R5J1fqok

### Get current user profile
GET http://localhost:5000/api/users/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjEsInV1aWQiOiJmMGE4ZTUzYy03NmJhLTQ0Y2YtOWRiMC03MDVjMGU0ZWE3MzEiLCJpYXQiOjE3NDQ1NTM3NjAsImV4cCI6MTc0NDU1NDY2MH0.tr9dizcDA8QjL0DH0_9gwiYtfITFUd-ovDLB4cLorSU

### Get user by UUID
GET http://localhost:5000/api/users/f0a8e53c-76ba-44cf-9db0-705c0e4ea731 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjEsInV1aWQiOiJmMGE4ZTUzYy03NmJhLTQ0Y2YtOWRiMC03MDVjMGU0ZWE3MzEiLCJpYXQiOjE3NDQ1NTM3NjAsImV4cCI6MTc0NDU1NDY2MH0.tr9dizcDA8QjL0DH0_9gwiYtfITFUd-ovDLB4cLorSU

### Update user by UUID
PATCH http://localhost:5000/api/users/f0a8e53c-76ba-44cf-9db0-705c0e4ea731 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjEsInV1aWQiOiJmMGE4ZTUzYy03NmJhLTQ0Y2YtOWRiMC03MDVjMGU0ZWE3MzEiLCJpYXQiOjE3NDQ1NTM3NjAsImV4cCI6MTc0NDU1NDY2MH0.tr9dizcDA8QjL0DH0_9gwiYtfITFUd-ovDLB4cLorSU

{
  "fullName": "Updated User",
  "email": "Updated.User@GMAIL.com"
}

### Delete user by UUID
DELETE http://localhost:5000/api/users/f0a8e53c-76ba-44cf-9db0-705c0e4ea731 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjEsInV1aWQiOiJmMGE4ZTUzYy03NmJhLTQ0Y2YtOWRiMC03MDVjMGU0ZWE3MzEiLCJpYXQiOjE3NDQ1NTM3NjAsImV4cCI6MTc0NDU1NDY2MH0.tr9dizcDA8QjL0DH0_9gwiYtfITFUd-ovDLB4cLorSU
